### ISSUE TITLE
[Feature Request] 'Smart' Backup Retention Option

### ISSUE THREAD

**Issue by rekonnected** [jneilliii/OctoPrint-BackupScheduler#4] opened 2020-09-21 18:45 UTC
One unrelated data backup program I use, [Duplicati](https://www.duplicati.com/), has a feature known as ['Smart' Backup Retention](https://forum.duplicati.com/t/new-retention-policy-deletes-old-backups-in-a-smart-way/2195), where it retains the following:

- 1 backup for each of the last 7 days
- 1 backup for each of the last 4 weeks
- 1 backup for each of the last 12 months

It may be a bit overkill to back up your instance every day, but some people may back up that often, so it may be a good idea to include the 7-day interval anyway. Either way, having a 'smart' retention system could help manage disk space efficiently and effectively.

**Comment by jneilliii** [comment] 2020-09-21 19:14
Kind of a duplicate of #2

**Comment by rekonnected** [comment] 2020-09-21 21:19
#2 is primarily for having multiple schedules of backing up, whereas this is more a strategy for managing backups already taken.

**Comment by jneilliii** [comment] 2020-09-21 22:35
Yeah, I understand the son/father/grandfather concept for backups and is not a bad idea for a future release. For now though I just wanted to get something out there as there seemed to be a high demand for this scheduling aspect.

**Comment by Lumute** [comment] 2020-09-22 15:08
+1 to add some kind of retention with automatic backup deletion to the plugin. Maybe it would be more logical to implement this before multiple schedules, then extend it when implementing that so each schedule has its own retention policy...

BTW, thanks so much for the great plugin! this is a feature that was really needed...

**Comment by jneilliii** [comment] 2020-09-22 15:23
I more than likely will develop the two features together, because I can see implementing a son/father/grandfather approach will require the deletions to be handled separately anyway so separating the schedules will be a prerequisite. Just have to wrap my head around the logic for each of the three stages, daily, weekly, monthly and how to handle the workflow. My initial thought is once the 3 backup options are split, adding a `retain for x` option to each of those would allow for easier handling of the deletions. The only thing I think will be a hurdle is figuring out which of the backups were run for each of the schedules, so in the long run may have to incorporate a logging of the backup names as well to prevent any deletion of manually created backups, etc.

**Closed** 2020-09-29 04:40 UTC
Labels: feature request

**Comment by jneilliii** [comment] 2020-09-29 04:45
The latest release version 0.0.3 incorporated options for remedial backup retention.
