### ISSUE TITLE
[FR]: Automatic downloads of backups

### ISSUE THREAD

**Issue by KenLucke** [jneilliii/OctoPrint-BackupScheduler#9] opened 2020-09-23 17:53 UTC
**Is your feature request related to a problem? Please describe.**
I'm a freak for backing things up.  I love this plugin, but downloading all the backups to the local drive is a PITA, especially as you have to do them one at a time because you can't select multiples for download the way can for deletions

**Describe the solution you'd like**
A way to select a folder on the local computer running OP (so that it's not just automatically the Downloads folder, so that they don't clog that folder and get lost in the shuffle, and can be easily located) and having the logs automatically downloaded, with or without retention on the computer(usually a Pi) running OP.  This would enable you to save them locally rather than taking up room on the Pi (and forgetting you have this running and sucking down all sorts of drive space)

**Describe alternatives you've considered**
Not having this :)

**Additional context**

**Comment by jneilliii** [comment] 2020-09-23 18:38
Well, we have two requests here. One of retention policy which is a duplicate of #4 and one of transferring backups to another location, duplicate of #5 and #3. The second request was the reason for the Google Drive Backup plugin (which actually came prior to this plugin) that will be available with OctoPrint 1.5.0. The idea is to separate the two because they are functionally different things.

**Closed by jneilliii** 2020-09-23 18:38 UTC

**Comment by KenLucke** [comment] 2020-09-23 19:43
Well, that leaves me out.  I don't use Google ANYTHING. Google is evil.

**Comment by jneilliii** [comment] 2020-09-23 20:54
I understand, but there is the option for other plugin developers, maybe I will create one down the road, to do any type of file transfer of the backup zip.

**Comment by C0lemanjr** [comment] 2021-01-20 17:47
May I ask the directory in which the automatic backup scheduler stores the images, please?

**Comment by jneilliii** [comment] 2021-01-20 18:26
It's the default path that OctoPrint saves them. If you are using OctoPi, the path is `/home/pi/.octoprint/data/backup`.

**Comment by C0lemanjr** [comment] 2021-01-20 19:26
Thank you
