### ISSUE TITLE
[BUG]: Retain option doesn't work

### ISSUE THREAD

**Issue by csm10495** [jneilliii/OctoPrint-BackupScheduler#29] opened 2024-12-22 01:55 UTC
**Describe the bug**
Hi, 

I think the retain option doesn't seem to have an effect. I have to manually go and delete old backups even if retain is set to something like 5. 

I noticed in the readme on https://plugins.octoprint.org/plugins/backupscheduler/ it says: 

```
WARNING: This plugin currently does not monitor your disk usage or limit/reduce your backup count in any way.
```

So maybe this is expected behavior? If so why not just get rid of the retain option?

**Expected behavior**
If retain is set to 5, only keep the 5 latest backups in the given category (like daily or montly)

**Debug Log**
NA? I think the plugin doesn't make logs. (The example is for a different plugin.)

**Screenshots**
![image](https://github.com/user-attachments/assets/98405683-8343-4b33-9c7f-8058d9633431)

**Firmware and Version**
Octoprint Version 1.10.3.

**Comment by jneilliii** [comment] 2024-12-22 02:59
That retain option is intended to delete older backups, the work is done here: <https://github.com/jneilliii/OctoPrint-BackupScheduler/blob/5413640324960a026946614e1faccd2e73bb91c2/octoprint_backupscheduler/__init__.py#L218-L222>

If it's not working as intended there could have been something that was broken in the last version release, please enable debug logging for the plugin and let a backup cycle complete and then share octoprint.log.

**Comment by csm10495** [comment] 2024-12-22 03:02
Enabled logging. Will come back in the next day or so with results.

**Comment by csm10495** [comment] 2024-12-28 07:09
Ok I don't think its working: 
```
pi@pi2:~/.octoprint/logs $ grep -R octoprint.plugins.backupscheduler .
./octoprint.log.2024-12-25:2024-12-26 01:23:40,599 - octoprint.plugins.backupscheduler - DEBUG - Performing daily_backups with exclusions: ['timelapse'] as octoprint-daily-20241226-012340.zip.
./octoprint.log.2024-12-25:2024-12-26 01:23:40,644 - octoprint.plugins.backupscheduler - DEBUG - Deleting backups: ['octoprint-daily-20241222-012332.zip']
./octoprint.log.2024-12-25:2024-12-26 01:23:41,152 - octoprint.plugins.backupscheduler - DEBUG - ['octoprint-daily-20241223-043426.zip', 'octoprint-daily-20241224-013013.zip', 'octoprint-daily-20241225-012339.zip', 'octoprint-daily-20241226-012340.zip']
./octoprint.log.2024-12-25:2024-12-26 01:32:33,996 - octoprint.plugins.backupscheduler - DEBUG - Plugin message: {'notifyTitle': '', 'clear_notification': True}
./octoprint.log.2024-12-22:2024-12-22 01:23:32,595 - octoprint.plugins.backupscheduler - DEBUG - Performing daily_backups with exclusions: ['timelapse'] as octoprint-daily-20241222-012332.zip.
./octoprint.log.2024-12-22:2024-12-22 01:23:32,827 - octoprint.plugins.backupscheduler - DEBUG - Deleting backups: ['octoprint-daily-20241217-012325.zip', 'octoprint-daily-20241218-012326.zip']
./octoprint.log.2024-12-22:2024-12-22 01:23:33,351 - octoprint.plugins.backupscheduler - DEBUG - ['octoprint-daily-20241219-012327.zip', 'octoprint-daily-20241220-012329.zip', 'octoprint-daily-20241221-012330.zip', 'octoprint-daily-20241222-012332.zip']
./octoprint.log.2024-12-22:2024-12-22 01:31:34,482 - octoprint.plugins.backupscheduler - DEBUG - Plugin message: {'notifyTitle': '', 'clear_notification': True}
./octoprint.log.2024-12-22:2024-12-22 21:45:16,664 - octoprint.plugins.backupscheduler - DEBUG - Clearing scheduled jobs.
./octoprint.log.2024-12-22:2024-12-22 21:45:16,776 - octoprint.plugins.backupscheduler - DEBUG - Scheduling daily backup for 01:23.
./octoprint.log.2024-12-22:2024-12-22 21:45:16,809 - octoprint.plugins.backupscheduler - DEBUG - Scheduling monthly backup for 01:25.
./octoprint.log.2024-12-22:2024-12-23 01:23:16,981 - octoprint.plugins.backupscheduler - DEBUG - Skipping daily_backups for now because a print is ongoing.
./octoprint.log.2024-12-22:2024-12-23 01:25:16,984 - octoprint.plugins.backupscheduler - DEBUG - Skipping monthly_backups for now because a print is ongoing.
./octoprint.log.2024-12-22:2024-12-23 04:34:26,397 - octoprint.plugins.backupscheduler - DEBUG - Starting daily_backups after print completion.
./octoprint.log.2024-12-22:2024-12-23 04:34:26,416 - octoprint.plugins.backupscheduler - DEBUG - Performing daily_backups with exclusions: ['timelapse'] as octoprint-daily-20241223-043426.zip.
./octoprint.log.2024-12-22:2024-12-23 04:34:26,441 - octoprint.plugins.backupscheduler - DEBUG - Deleting backups: ['octoprint-daily-20241219-012327.zip']
./octoprint.log.2024-12-22:2024-12-23 04:34:26,883 - octoprint.plugins.backupscheduler - DEBUG - ['octoprint-daily-20241220-012329.zip', 'octoprint-daily-20241221-012330.zip', 'octoprint-daily-20241222-012332.zip', 'octoprint-daily-20241223-043426.zip']
./octoprint.log.2024-12-22:2024-12-23 04:43:42,044 - octoprint.plugins.backupscheduler - DEBUG - Plugin message: {'notifyTitle': '', 'clear_notification': True}
./octoprint.log:2024-12-27 16:36:25,969 - octoprint.plugins.backupscheduler - DEBUG - Clearing scheduled jobs.
./octoprint.log:2024-12-27 16:36:26,123 - octoprint.plugins.backupscheduler - DEBUG - Scheduling daily backup for 01:23.
./octoprint.log:2024-12-27 16:36:26,155 - octoprint.plugins.backupscheduler - DEBUG - Scheduling monthly backup for 01:25.
./octoprint.log:2024-12-27 17:24:34,354 - octoprint.plugins.backupscheduler - DEBUG - Clearing scheduled jobs.
./octoprint.log:2024-12-27 17:24:34,451 - octoprint.plugins.backupscheduler - DEBUG - Scheduling daily backup for 01:23.
./octoprint.log:2024-12-27 17:24:34,463 - octoprint.plugins.backupscheduler - DEBUG - Scheduling monthly backup for 01:25.
./octoprint.log:2024-12-27 17:43:03,019 - octoprint.plugins.backupscheduler - DEBUG - Clearing scheduled jobs.
./octoprint.log:2024-12-27 17:43:03,029 - octoprint.plugins.backupscheduler - DEBUG - Scheduling daily backup for 01:23.
./octoprint.log:2024-12-27 17:43:03,130 - octoprint.plugins.backupscheduler - DEBUG - Scheduling monthly backup for 01:25.
./octoprint.log:2024-12-27 22:43:47,499 - octoprint.plugins.backupscheduler - DEBUG - Clearing scheduled jobs.
./octoprint.log:2024-12-27 22:43:47,617 - octoprint.plugins.backupscheduler - DEBUG - Scheduling daily backup for 01:23.
./octoprint.log:2024-12-27 22:43:47,642 - octoprint.plugins.backupscheduler - DEBUG - Scheduling monthly backup for 01:25.
./octoprint.log:2024-12-27 22:50:45,679 - octoprint.plugins.backupscheduler - DEBUG - Clearing scheduled jobs.
./octoprint.log:2024-12-27 22:50:45,774 - octoprint.plugins.backupscheduler - DEBUG - Scheduling daily backup for 01:23.
./octoprint.log:2024-12-27 22:50:45,862 - octoprint.plugins.backupscheduler - DEBUG - Scheduling monthly backup for 01:25.
./octoprint.log:2024-12-27 22:53:08,683 - octoprint.plugins.backupscheduler - DEBUG - Clearing scheduled jobs.
./octoprint.log:2024-12-27 22:53:08,691 - octoprint.plugins.backupscheduler - DEBUG - Scheduling daily backup for 01:23.
./octoprint.log:2024-12-27 22:53:08,803 - octoprint.plugins.backupscheduler - DEBUG - Scheduling monthly backup for 01:25.
./octoprint.log:2024-12-27 23:00:30,093 - octoprint.plugins.backupscheduler - DEBUG - Clearing scheduled jobs.
./octoprint.log:2024-12-27 23:00:30,102 - octoprint.plugins.backupscheduler - DEBUG - Scheduling daily backup for 01:23.
./octoprint.log:2024-12-27 23:00:30,214 - octoprint.plugins.backupscheduler - DEBUG - Scheduling monthly backup for 01:25.
./octoprint.log:2024-12-27 23:06:20,207 - octoprint.plugins.backupscheduler - DEBUG - Clearing scheduled jobs.
./octoprint.log:2024-12-27 23:06:20,214 - octoprint.plugins.backupscheduler - DEBUG - Scheduling daily backup for 01:23.
./octoprint.log:2024-12-27 23:06:20,321 - octoprint.plugins.backupscheduler - DEBUG - Scheduling monthly backup for 01:25.
./octoprint.log.2024-12-20:2024-12-21 19:01:47,797 - octoprint.plugins.logging - INFO - Setting logger octoprint.plugins.backupscheduler level to DEBUG
./octoprint.log.2024-12-24:2024-12-24 01:23:18,001 - octoprint.plugins.backupscheduler - DEBUG - Skipping daily_backups for now because a print is ongoing.
./octoprint.log.2024-12-24:2024-12-24 01:25:18,003 - octoprint.plugins.backupscheduler - DEBUG - Skipping monthly_backups for now because a print is ongoing.
./octoprint.log.2024-12-24:2024-12-24 01:30:13,258 - octoprint.plugins.backupscheduler - DEBUG - Starting monthly_backups after print completion.
./octoprint.log.2024-12-24:2024-12-24 01:30:13,262 - octoprint.plugins.backupscheduler - DEBUG - Starting daily_backups after print completion.
./octoprint.log.2024-12-24:2024-12-24 01:30:13,276 - octoprint.plugins.backupscheduler - DEBUG - Performing daily_backups with exclusions: ['timelapse'] as octoprint-daily-20241224-013013.zip.
./octoprint.log.2024-12-24:2024-12-24 01:30:13,304 - octoprint.plugins.backupscheduler - DEBUG - Deleting backups: ['octoprint-daily-20241220-012329.zip']
./octoprint.log.2024-12-24:2024-12-24 01:30:13,726 - octoprint.plugins.backupscheduler - DEBUG - ['octoprint-daily-20241221-012330.zip', 'octoprint-daily-20241222-012332.zip', 'octoprint-daily-20241223-043426.zip', 'octoprint-daily-20241224-013013.zip']
./octoprint.log.2024-12-24:2024-12-24 01:39:10,475 - octoprint.plugins.backupscheduler - DEBUG - Plugin message: {'notifyTitle': '', 'clear_notification': True}
./octoprint.log.2024-12-24:2024-12-24 15:05:38,683 - octoprint.plugins.backupscheduler - DEBUG - Clearing scheduled jobs.
./octoprint.log.2024-12-24:2024-12-24 15:05:38,697 - octoprint.plugins.backupscheduler - DEBUG - Scheduling daily backup for 01:23.
./octoprint.log.2024-12-24:2024-12-24 15:05:38,743 - octoprint.plugins.backupscheduler - DEBUG - Scheduling monthly backup for 01:25.
./octoprint.log.2024-12-24:2024-12-25 01:23:39,223 - octoprint.plugins.backupscheduler - DEBUG - Performing daily_backups with exclusions: ['timelapse'] as octoprint-daily-20241225-012339.zip.
./octoprint.log.2024-12-24:2024-12-25 01:23:39,292 - octoprint.plugins.backupscheduler - DEBUG - Deleting backups: ['octoprint-daily-20241221-012330.zip']
./octoprint.log.2024-12-24:2024-12-25 01:23:39,704 - octoprint.plugins.backupscheduler - DEBUG - ['octoprint-daily-20241222-012332.zip', 'octoprint-daily-20241223-043426.zip', 'octoprint-daily-20241224-013013.zip', 'octoprint-daily-20241225-012339.zip']
./octoprint.log.2024-12-24:2024-12-25 01:31:58,472 - octoprint.plugins.backupscheduler - DEBUG - Plugin message: {'notifyTitle': '', 'clear_notification': True}
./octoprint.log.2024-12-26:2024-12-27 01:23:42,213 - octoprint.plugins.backupscheduler - DEBUG - Skipping daily_backups for now because a print is ongoing.
./octoprint.log.2024-12-26:2024-12-27 01:25:42,219 - octoprint.plugins.backupscheduler - DEBUG - Skipping monthly_backups for now because a print is ongoing.
./octoprint.log.2024-12-26:2024-12-27 08:48:32,306 - octoprint.plugins.backupscheduler - DEBUG - Starting daily_backups after print completion.
./octoprint.log.2024-12-26:2024-12-27 08:48:32,320 - octoprint.plugins.backupscheduler - DEBUG - Performing daily_backups with exclusions: ['timelapse'] as octoprint-daily-20241227-084832.zip.
./octoprint.log.2024-12-26:2024-12-27 08:48:32,363 - octoprint.plugins.backupscheduler - DEBUG - Deleting backups: ['octoprint-daily-20241223-043426.zip']
./octoprint.log.2024-12-26:2024-12-27 08:48:32,766 - octoprint.plugins.backupscheduler - DEBUG - ['octoprint-daily-20241224-013013.zip', 'octoprint-daily-20241225-012339.zip', 'octoprint-daily-20241226-012340.zip', 'octoprint-daily-20241227-084832.zip']
./octoprint.log.2024-12-26:2024-12-27 08:58:19,676 - octoprint.plugins.backupscheduler - DEBUG - Plugin message: {'notifyTitle': '', 'clear_notification': True}
```

I  have daily retain set to 4, though now i have 9 daily backups: 
![image](https://github.com/user-attachments/assets/9eede1c7-e93c-440c-9a10-08bb58014251)

It sort of looks like it thinks it deletes them but then doesn't.

**Comment by jneilliii** [comment] 2024-12-30 05:05
It would be extremely helpful to get full octoprint.log and not just the grep snippets that you are providing. You can download the whole octoprint.log from the logging section of the web ui and upload it here using the paperclip icon in a comment.

**Comment by csm10495** [comment] 2024-12-30 05:37
Sure thing. Uploaded the current log file and the old one before it: 

[octoprint.log](https://github.com/user-attachments/files/18272229/octoprint.log)

**Comment by jneilliii** [comment] 2024-12-30 05:53
Thanks, so I'm seeing the same thing in yours that I was seeing in mine and have a suspicion of what might be causing it, but have reached on Discord to see if anyone else has seen this behavior before.

**Comment by jneilliii** [comment] 2024-12-30 19:02
should be fixed with above commit and made available in version 0.2.2. There was some weird race condition preventing the delete_backup helper from running as expected.

**Closed by jneilliii** 2024-12-30 19:02 UTC

**Comment by csm10495** [comment] 2024-12-31 02:03
Thanks. This may be a red-herring, though a bit after updating the plugin I looked at the backups and see 3:
![image](https://github.com/user-attachments/assets/3f4f332c-873b-4d06-82ea-8bb3d3d2f4ca)

Though my settings say 4 retained dailies and a monthly: 
![image](https://github.com/user-attachments/assets/3237f378-945c-424d-b90a-64dabb9b2e6c)

I had the monthly there before (see my older screenshots). Is there some sort of off-by-one or other issue leading to early deletions? 

Attaching a fresh octoprint.log file in case it could be helpful: 
[octoprint (1).log](https://github.com/user-attachments/files/18278776/octoprint.1.log)

**Comment by jneilliii** [comment] 2024-12-31 03:58
It won't delete old backups that had been missed from the previous retention, so you'll have to manually remove those and then moving forward the retention settings should kick in and keep only the configured number.

**Comment by csm10495** [comment] 2024-12-31 04:42
That seems odd since now I have below the retention count for daily and no monthlies.

**Comment by jneilliii** [comment] 2024-12-31 04:57
Oh sorry, misinterpreted/read what you said. That is odd those are missing, because the log definitely doesn't indicate a monthly backup being deleted by the plugin.
