### ISSUE TITLE
Feature Request Backup Path to an ftp folder or smb share

### ISSUE THREAD

**Issue by kalleknall** [jneilliii/OctoPrint-BackupScheduler#5] opened 2020-09-21 21:17 UTC
Great Idea ! 

an external Backup location would be nice.

THX for your Great Work with so many Plungins !

Christian

**Comment by jneilliii** [comment] 2020-09-21 22:33
I'm going to refer to this one as a duplicate of #3

**Closed by jneilliii** 2020-09-21 22:33 UTC
